name: Hieu Dao Trung
title: Hieu Dao Trung
subtitle: C++ is too easy so I learn Danish
description: "ğŸ“ BEng., MSc. Mechatronic Engineering<br>ğŸ’¼ Control System Engineer<br>ğŸ“ Aarhus, Denmark<br>ğŸ›« Ho Chi Minh city, Vietnam"
avatar: "assets/images/relax-face-portrait.png" # optional
email: hdt.foss@gmail.com

social:
  - icon: "github"
    url: "https://github.com/hiedt"
  - icon: "linkedin"
    url: "https://linkedin.com/in/hiedt"
  - icon: "mastodon"
    url: "https://mastodon.social/@hiedt"
  - icon: "medium"
    url: "https://hieudaotrung.medium.com/"

projects:
  - title: "A Primer on Modern Control Algorithms"
    subtitle: "with Julia code samples"
    description: "My handwritten notes after 30 ECTS of graduate-level control courses, by student, for students."
    url: "https://apomca.readthedocs.io"
    thumbnail: "assets/images/APOMCA version 1.png"
    tags: ["control", "algorithm", "julia"]
  - title: "Data Structures and Algorithm Analysis in Zig"
    subtitle: ""
    description: "Based on the original series of Mark Allen Weiss, this book flashbacks my deep dive into the realm of low-level system programming."
    url: "https://project2.com"
    thumbnail: "https://via.placeholder.com/150"
    tags: ["tag1", "tag2", "tag3"]
  - title: "The Law That Governs All Physics"
    subtitle: "An introduction to Calculus of Variations"
    description: "Why does light travel on a straight line? Is energy actually conserved? And how are these two questions related?"
    url: "https://project1.com"
    thumbnail: "https://via.placeholder.com/150"
    tags: ["physics", "calculus", "math", "variational"]
